apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: webhook
  namespace: default
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/AdminTurnedDevOps/GoWebAPI.git'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'ruby:2.7'
        namespace: openshift
      env: []
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    - type: webhook